#!/bin/bash
#
# Coderaft
# Simple tool to quickly setup new VPS servers to deploy your code.
# https://github.com/diogocasado/coderaft
#
SERVICE="dummy"
DESCRIPTION="This is dummy project written in Node.js to showcase Coderaft."
LOCATION="/"
PROXY_PASS="http://unix:/run/dummy.sock"
